In [61]:
import numpy as np  

In [70]:
vec = np.random.randn(1,8)
vec2 = np.random.randn(1,8)
projection_mat = np.random.randn(4, 8)
print("vec1", vec)
print("vec2", vec2)
compressed_vec1 = np.dot(projection_mat, vec.T).T
compressed_vec2 = np.dot(projection_mat, vec2.T).T
print("compressed_vec1", compressed_vec1)
print("compressed_vec2", compressed_vec2)

vec1 [[ 0.00810847 -1.45667206 -0.64782867 -0.62938774  0.28535454  0.99353375
  -0.25334798  0.22420052]]
vec2 [[-0.02738609  0.02225765  0.45460677 -0.17382567  0.73159416 -0.0988793
   0.49947495  1.21354151]]
compressed_vec1 [[-1.1213429  -0.77420553 -1.04170849 -3.33935058]]
compressed_vec2 [[-0.2557735   0.60516145  0.37639743 -0.58047966]]


In [110]:
mat = vec
# print(vec)
mat = np.concatenate((mat, vec2))
print(mat)
mat[1]

[[ 0.00810847 -1.45667206 -0.64782867 -0.62938774  0.28535454  0.99353375
  -0.25334798  0.22420052]
 [-0.02738609  0.02225765  0.45460677 -0.17382567  0.73159416 -0.0988793
   0.49947495  1.21354151]]


array([-0.02738609,  0.02225765,  0.45460677, -0.17382567,  0.73159416,
       -0.0988793 ,  0.49947495,  1.21354151])

In [71]:
compressed_mat = compressed_vec1.reshape(-1,1)
compressed_mat = np.concatenate((compressed_mat, compressed_vec2.reshape(-1,1)), axis=1)
print("compressed mat:", compressed_mat)

compressed mat: [[-1.1213429  -0.2557735 ]
 [-0.77420553  0.60516145]
 [-1.04170849  0.37639743]
 [-3.33935058 -0.58047966]]


In [118]:
query =  np.random.randn(1,8)
projected_query = np.dot(projection_mat, query.T).T
print(projected_query)
# similarities = np.sum((compressed_mat - projected_query) ** 2, axis=1)
distances = np.sum((compressed_mat - projected_query.reshape(-1, 1))**2, axis=0)
dot_prods = np.dot(projected_query, compressed_mat)
similarities = dot_prods / (np.linalg.norm(compressed_mat, axis=0) * np.linalg.norm(projected_query))
print("l2", distances)
print("cos", similarities)
vec_indexl2 = np.argmin(distances)
vec_index_cos = np.argmax(similarities)
best_vecl2 = compressed_mat[:, vec_indexl2]
best_vec_cos = compressed_mat[:, vec_index_cos]
print("best_vec_l2:", best_vecl2)
print("best_vec_cos:", best_vec_cos)

[[-3.59463287 -2.2040294  -1.37286256 -2.75750267]]
l2 [ 8.60976958 26.83887487]
cos [[0.83534756 0.134392  ]]
best_vec_l2: [-1.1213429  -0.77420553 -1.04170849 -3.33935058]
best_vec_cos: [-1.1213429  -0.77420553 -1.04170849 -3.33935058]


In [40]:
if self.dist_func == "l2_squared":
                similarities = np.sum((self.compressed_mat - projected_query) ** 2, axis=1)
            elif self.dist_func == "cosine":
                similarities = np.dot(self.compressed_mat, projected_query) / (
                    np.linalg.norm(self.compressed_mat, axis=1) * np.linalg.norm(projected_query)
                )

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [59]:
import numpy as np

def l2_squared_distance(vector, matrix):
    # Calculate L2 squared distance between the vector and each column of the matrix
    print(vector.reshape(-1, 1))
    distances = np.sum((matrix - vector.reshape(-1, 1))**2, axis=0)
    return distances

# Example usage
vector = np.array([1, 2, 3, 4])  # Example 1x4 vector
print(vector)
matrix = [[1, 3], [2, 4], [3,1], [2, 2]]  # Example 4xm matrix, here m is 100
print(matrix)
similarities = l2_squared_distance(vector, matrix)

print("Similarities:", similarities)

[1 2 3 4]
[[1, 3], [2, 4], [3, 1], [2, 2]]
[[1]
 [2]
 [3]
 [4]]
Similarities: [ 4 16]
